# El deportista mejor pagado en 2020

In [5]:
import numpy as np 
import pandas as pd 

In [6]:
df = pd.read_csv("Forbes Richest Atheletes (Forbes Richest Athletes 1990-2020) (3).csv")
df.head()

S.NO               Name Nationality  Current Rank Previous Year Rank  \
0     1         Mike Tyson         USA             1                NaN   
1     2     Buster Douglas         USA             2                NaN   
2     3  Sugar Ray Leonard         USA             3                NaN   
3     4       Ayrton Senna      Brazil             4                NaN   
4     5        Alain Prost      France             5                NaN   

         Sport  Year  earnings ($ million)  
0       boxing  1990                  28.6  
1       boxing  1990                  26.0  
2       boxing  1990                  13.0  
3  auto racing  1990                  10.0  
4  auto racing  1990                   9.0

In [9]:
df1 = df.copy()
df1.drop('S.NO',axis=1,inplace=True)
df1.head()

Name Nationality  Current Rank Previous Year Rank  \
0         Mike Tyson         USA             1                NaN   
1     Buster Douglas         USA             2                NaN   
2  Sugar Ray Leonard         USA             3                NaN   
3       Ayrton Senna      Brazil             4                NaN   
4        Alain Prost      France             5                NaN   

         Sport  Year  earnings ($ million)  
0       BOXING  1990                  28.6  
1       BOXING  1990                  26.0  
2       BOXING  1990                  13.0  
3  AUTO RACING  1990                  10.0  
4  AUTO RACING  1990                   9.0

## Análisis previo

In [46]:
df1["Sport"] = df1["Sport"].str.upper()

In [47]:
# ¿Cuantos deportes hay?
print("El dataset incluye los los siguientes deportes:", set(df1["Sport"].sort_values(ascending=True)))

print("Son ",len(set(df1["Sport"].sort_values(ascending=True))), " categorías de deporte en total")

El dataset incluye los los siguientes deportes: {'BASEBALL', 'AUTO RACING', 'MMA', 'NASCAR', 'ICE HOCKEY', 'BOXING', 'BASKETBALL', 'TENNIS', 'AMERICAN FOOTBALL / BASEBALL', 'SOCCER', 'GOLF', 'AMERICAN FOOTBALL', 'AUTO RACING (NASCAR)', 'MOTORCYCLE GP', 'NFL', 'F1 MOTORSPORTS', 'CYCLING', 'F1 RACING', 'HOCKEY', 'NBA'}
Son  20  categorías de deporte en total


"Aaron Rogers" debería estar registrado como "Aaron Rodgers"

In [37]:
df1[df1["Name"] =="Aaron Rogers"]

Empty DataFrame
Columns: [Name, Nationality, Current Rank, Previous Year Rank, Sport, Year, earnings ($ million)]
Index: []

In [38]:
df1[df1["Name"] =="Aaron Rodgers"]

Name Nationality  Current Rank Previous Year Rank  \
226  Aaron Rodgers         USA             6                  ?   
287  Aaron Rodgers         USA             7                 ??   

                 Sport  Year  earnings ($ million)  
226  American Football  2013                  49.0  
287  American Football  2019                  89.3

In [36]:
df1["Name"] = df1["Name"].replace("Aaron Rogers", "Aaron Rodgers")

In [59]:
# ¿Cuántos deportistas incluye el dataset?

print("Existen ", len(set(df1["Name"].sort_values(ascending=True))), "atletas registrados en el dataset")

Existen  82 atletas registrados en el dataset


## 1. Deportistas cuyo ranking ha subido al menos dos lugares entre 2010 y 2020.

In [64]:
data2010_2020 = df1[df1["Year"] >=2010]
data2010_2020

Name Nationality  Current Rank Previous Year Rank  \
191       Tiger Woods         USA             1                  1   
192  Floyd Mayweather         USA             2                >10   
193       Kobe Bryant         USA             3                  2   
194    Phil Mickelson         USA             4                  6   
195     David Beckham          UK             5                  5   
..                ...         ...           ...                ...   
296     Stephen Curry         USA             6                  9   
297      Kevin Durant         USA             7                 10   
298       Tiger Woods         USA             8                 11   
299      Kirk Cousins         USA             9               >100   
300      Carson Wentz         USA            10               >100   

                 Sport  Year  earnings ($ million)  
191               GOLF  2010                 105.0  
192             BOXING  2010                  65.0  
193         BASKETBALL  2010                  48.0  
194               GOLF  2010                  46.0  
195             SOCCER  2010                  43.7  
..                 ...   ...                   ...  
296         BASKETBALL  2020                  74.4  
297         BASKETBALL  2020                  63.9  
298               GOLF  2020                  62.3  
299  AMERICAN FOOTBALL  2020                  60.5  
300  AMERICAN FOOTBALL  2020                  59.1  

[110 rows x 7 columns]

In [53]:
print("Hay", len(set(data2010_2020["Name"])), "deportistas en el periodo de analisis")


Hay 36 deportistas en el periodo de analisis


In [54]:

atletas2010_2020 = pd.DataFrame(data2010_2020["Name"].value_counts())
atletas2010_2020 = atletas2010_2020.rename(columns={"Name":"Registros"})
atletas2010_2020


Registros
Roger Federer              11
LeBron James               11
Cristiano Ronaldo          10
Lionel Messi                9
Tiger Woods                 7
Kobe Bryant                 7
Phil Mickelson              7
Kevin Durant                5
Floyd Mayweather            5
David Beckham               4
Stephen Curry               4
Manny Pacquiao              3
Neymar                      3
Matt Ryan                   2
Peyton Manning              1
Drew Brees                  1
Kirk Cousins                1
Aaron Rogers                1
Russell Wilson              1
Canelo Alvarez              1
Matthew Stafford            1
Eli Manning                 1
Conor McGregor              1
Lewis Hamilton              1
James Harden                1
Terrell Suggs               1
Rory McIlroy                1
Andrew Luck                 1
Jordan Spieth               1
Cam Newton                  1
Novak Djokovic              1
Alex Rodriguez              1
Michael Schumacher          1
Rafael Nadal                1
Aaron Rodgers               1
Carson Wentz                1

In [62]:
mas_de_dos_registros = atletas2010_2020[atletas2010_2020["Registros"] >= 2]
lista_dos_registros = mas_de_dos_registros.index.to_list()
(lista_dos_registros)


['Roger Federer',
 'LeBron James',
 'Cristiano Ronaldo',
 'Lionel Messi',
 'Tiger Woods',
 'Kobe Bryant',
 'Phil Mickelson',
 'Kevin Durant',
 'Floyd Mayweather',
 'David Beckham',
 'Stephen Curry',
 'Manny Pacquiao',
 'Neymar',
 'Matt Ryan']

Construyendo un DataFrame por jugador

In [56]:
Roger_Federer = data2010_2020[data2010_2020["Name"]== 'Roger Federer']
LeBron_James = data2010_2020[data2010_2020["Name"]== 'LeBron James']
Cristiano_Ronaldo = data2010_2020[data2010_2020["Name"]== 'Cristiano Ronaldo']
Lionel_Messi =data2010_2020[data2010_2020["Name"]== 'Lionel Messi']
Tiger_Woods = data2010_2020[data2010_2020["Name"]== 'Tiger Woods']
Kobe_Bryant = data2010_2020[data2010_2020["Name"]== 'Kobe Bryant']
Phil_Mickelson = data2010_2020[data2010_2020["Name"]== 'Phil Mickelson']
Kevin_Durant = data2010_2020[data2010_2020["Name"]== 'Kevin Durant']
Floyd_Mayweather = data2010_2020[data2010_2020["Name"]== 'Floyd Mayweather']
Stephen_Curry = data2010_2020[data2010_2020["Name"]== 'Stephen Curry']
David_Beckham = data2010_2020[data2010_2020["Name"]== 'David Beckham']
Neymar = data2010_2020[data2010_2020["Name"]== 'Neymar']
Aaron_Rodgers = data2010_2020[data2010_2020["Name"]== 'Aaron Rodgers']
Manny_Pacquiao = data2010_2020[data2010_2020["Name"]== 'Manny Pacquiao']
Matt_Ryan = data2010_2020[data2010_2020["Name"]== 'Matt Ryan']

Fijar el indice

In [66]:
Roger_Federer.index = Roger_Federer["Year"]

LeBron_James.index =LeBron_James["Year"]
Cristiano_Ronaldo.index =Cristiano_Ronaldo["Year"]
Lionel_Messi.index = Lionel_Messi["Year"]
Tiger_Woods.index = Tiger_Woods["Year"]
Kobe_Bryant.index = Kobe_Bryant["Year"]
Phil_Mickelson.index = Phil_Mickelson["Year"]
Kevin_Durant.index = Kevin_Durant["Year"]
Floyd_Mayweather.index = Floyd_Mayweather["Year"]
Stephen_Curry.index = Stephen_Curry["Year"]
David_Beckham.index = David_Beckham["Year"]
Neymar.index = Neymar["Year"]
Aaron_Rodgers.index = Aaron_Rodgers["Year"]
Manny_Pacquiao.index = Manny_Pacquiao["Year"]
Matt_Ryan.index  = Matt_Ryan["Year"]


Agregando columnas

In [71]:
distribucion = pd.DataFrame(set(data2010_2020["Year"]))
distribucion

0
0   2016
1   2017
2   2018
3   2019
4   2020
5   2010
6   2011
7   2012
8   2013
9   2014
10  2015

In [60]:
distribucion["Roger Federer"] = Roger_Federer["Current Rank"]
distribucion["LeBron James"] = LeBron_James["Current Rank"]
distribucion["Cristiano Ronaldo"] = Cristiano_Ronaldo["Current Rank"]
distribucion["Lionel Messi"] = Lionel_Messi["Current Rank"]
distribucion["Tiger Woods"] = Tiger_Woods["Current Rank"]
distribucion["Kobe Bryant"] = Kobe_Bryant["Current Rank"]
distribucion["Phil Mickelson"] = Phil_Mickelson["Current Rank"]
distribucion["Kevin Durant"] = Kevin_Durant["Current Rank"]
distribucion["Floyd Mayweather"] = Floyd_Mayweather["Current Rank"]
distribucion["Stephen Curry"] = Stephen_Curry["Current Rank"]
distribucion["David Beckham"] = David_Beckham["Current Rank"]
distribucion["Neymar"] = Neymar["Current Rank"]
distribucion["Aaron Rodgers"] = Aaron_Rodgers["Current Rank"]
distribucion["Manny Pacquiao"] = Manny_Pacquiao["Current Rank"]
distribucion["Matt Ryan"] = Matt_Ryan["Current Rank"]


NameError: name 'distribucion' is not defined

In [67]:
distribucion

191    2010
192    2010
193    2010
194    2010
195    2010
       ... 
296    2020
297    2020
298    2020
299    2020
300    2020
Name: Year, Length: 110, dtype: int64

In [ ]:
dist

### El resultado son los deportistas de la siguiente tabla

In [234]:
distribucion.describe()

Roger Federer  LeBron James  Cristiano Ronaldo  Lionel Messi  \
count      11.000000     11.000000           10.00000      9.000000   
mean        4.545455      4.636364            3.90000      4.333333   
std         1.863525      1.911687            3.17805      3.354102   
min         1.000000      2.000000            1.00000      1.000000   
25%         4.000000      3.000000            2.00000      2.000000   
50%         5.000000      4.000000            2.50000      3.000000   
75%         5.500000      6.000000            6.00000      4.000000   
max         7.000000      8.000000            9.00000     10.000000   

       Tiger Woods  Kobe Bryant  Phil Mickelson  Kevin Durant  \
count     7.000000     7.000000        7.000000       5.00000   
mean      4.142857     5.571429        6.714286       6.80000   
std       3.484660     3.309438        1.603567       2.04939   
min       1.000000     2.000000        4.000000       5.00000   
25%       1.000000     3.000000        6.000000       5.00000   
50%       3.000000     5.000000        7.000000       7.00000   
75%       7.000000     8.000000        8.000000       7.00000   
max       9.000000    10.000000        8.000000      10.00000   

       Floyd Mayweather  Stephen Curry  David Beckham  Neymar  Aaron Rodgers  \
count          5.000000       4.000000           4.00     3.0       2.000000   
mean           1.200000       7.750000           6.75     4.0       6.500000   
std            0.447214       1.258306           1.50     1.0       0.707107   
min            1.000000       6.000000           5.00     3.0       6.000000   
25%            1.000000       7.500000           5.75     3.5       6.250000   
50%            1.000000       8.000000           7.00     4.0       6.500000   
75%            1.000000       8.250000           8.00     4.5       6.750000   
max            2.000000       9.000000           8.00     5.0       7.000000   

       Manny Pacquiao  Matt Ryan  
count        3.000000   2.000000  
mean         4.000000   9.500000  
std          3.464102   0.707107  
min          2.000000   9.000000  
25%          2.000000   9.250000  
50%          2.000000   9.500000  
75%          5.000000   9.750000  
max          8.000000  10.000000

## 2. Atleta con el menor número de apariciones y mayores ganancias.

In [482]:
df.head()

S.NO               Name Nationality  Current Rank Previous Year Rank  \
0     1         Mike Tyson         USA             1                NaN   
1     2     Buster Douglas         USA             2                NaN   
2     3  Sugar Ray Leonard         USA             3                NaN   
3     4       Ayrton Senna      Brazil             4                NaN   
4     5        Alain Prost      France             5                NaN   

         Sport  Year  earnings ($ million)  
0       boxing  1990                  28.6  
1       boxing  1990                  26.0  
2       boxing  1990                  13.0  
3  auto racing  1990                  10.0  
4  auto racing  1990                   9.0

## 3. Deporte y país con mayor número de atletas no rankeados que entraron en la lista de atletas mejor pagados.

In [430]:
df.head()

S.NO               Name Nationality  Current Rank Previous Year Rank  \
0     1         Mike Tyson         USA             1                NaN   
1     2     Buster Douglas         USA             2                NaN   
2     3  Sugar Ray Leonard         USA             3                NaN   
3     4       Ayrton Senna      Brazil             4                NaN   
4     5        Alain Prost      France             5                NaN   

         Sport  Year  earnings ($ million)  
0       boxing  1990                  28.6  
1       boxing  1990                  26.0  
2       boxing  1990                  13.0  
3  auto racing  1990                  10.0  
4  auto racing  1990                   9.0

In [440]:
df["Current Rank"].describe()

count    301.000000
mean       5.448505
std        2.850995
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       10.000000
Name: Current Rank, dtype: float64

In [41]:
no_rankeados = df[df["Previous Year Rank"].isna()]
no_rankeados["earnings ($ million)"].sort_values(ascending=False).head(10)

80     69.0
266    50.0
268    47.3
269    46.6
270    46.0
81     38.0
82     29.8
0      28.6
83     26.8
1      26.0
Name: earnings ($ million), dtype: float64

In [ ]:
no_rankeados[no_rankeados["earnings ($ million)"] == 69.0]
no_rankeados[no_rankeados["earnings ($ million)"] == 50.0]
no_rankeados[no_rankeados["earnings ($ million)"] == 47.3]
no_rankeados[no_rankeados["earnings ($ million)"] == 46.6]
no_rankeados[no_rankeados["earnings ($ million)"] == 46.0]
no_rankeados[no_rankeados["earnings ($ million)"] == 38.0]
no_rankeados[no_rankeados["earnings ($ million)"] == 29.8]
no_rankeados[no_rankeados["earnings ($ million)"] == 28.6]
no_rankeados[no_rankeados["earnings ($ million)"] == 26.8]
no_rankeados[no_rankeados["earnings ($ million)"] == 26.8]

In [481]:
no_rankeados[no_rankeados["earnings ($ million)"] == 69.0]

S.NO            Name Nationality  Current Rank Previous Year Rank  \
80    81  Michael Jordan         USA             1                NaN   

         Sport  Year  earnings ($ million)  
80  Basketball  1998                  69.0

In [480]:
no_rankeados[no_rankeados["earnings ($ million)"] == 50.0]

S.NO         Name Nationality  Current Rank Previous Year Rank  \
266   267  Andrew Luck         USA             6                NaN   

                 Sport  Year  earnings ($ million)  
266  American Football  2017                  50.0

In [479]:
no_rankeados[no_rankeados["earnings ($ million)"] == 47.3]

S.NO           Name Nationality  Current Rank Previous Year Rank  \
268   269  Stephen Curry         USA             8                NaN   

          Sport  Year  earnings ($ million)  
268  Basketball  2017                  47.3

In [478]:
no_rankeados[no_rankeados["earnings ($ million)"] == 46.6]

S.NO          Name Nationality  Current Rank Previous Year Rank  \
269   270  James Harden         USA             9                NaN   

          Sport  Year  earnings ($ million)  
269  Basketball  2017                  46.6

In [477]:
no_rankeados[no_rankeados["earnings ($ million)"] == 46.0]

S.NO            Name Nationality  Current Rank Previous Year Rank  \
270   271  Lewis Hamilton          UK            10                NaN   

           Sport  Year  earnings ($ million)  
270  auto racing  2017                  46.0

In [476]:
no_rankeados[no_rankeados["earnings ($ million)"] == 38.0]

S.NO                Name Nationality  Current Rank Previous Year Rank  \
81    82  Michael Schumacher     Germany             2                NaN   

             Sport  Year  earnings ($ million)  
81  F1 Motorsports  1998                  38.0

In [475]:
no_rankeados[no_rankeados["earnings ($ million)"] == 29.8]

S.NO            Name Nationality  Current Rank Previous Year Rank  \
82    83  Sergei Federov      Russia             3                NaN   

         Sport  Year  earnings ($ million)  
82  Ice Hockey  1998                  29.8

In [474]:
no_rankeados[no_rankeados["earnings ($ million)"] == 28.6]

S.NO        Name Nationality  Current Rank Previous Year Rank   Sport  \
0     1  Mike Tyson         USA             1                NaN  boxing   

   Year  earnings ($ million)  
0  1990                  28.6

In [473]:
no_rankeados[no_rankeados["earnings ($ million)"] == 26.8]

S.NO         Name Nationality  Current Rank Previous Year Rank Sport  \
83    84  Tiger Woods         USA             4                NaN  Golf   

    Year  earnings ($ million)  
83  1998                  26.8

In [472]:
no_rankeados[no_rankeados["earnings ($ million)"] == 26.0]

S.NO            Name Nationality  Current Rank Previous Year Rank   Sport  \
1     2  Buster Douglas         USA             2                NaN  boxing   

   Year  earnings ($ million)  
1  1990                  26.0

### La respuesta es USA y Basketball

## 4. País con mayor número de deportes con atletas en el conjunto de datos.

In [ ]:
set(USA["Sport"])

In [2]:
Argentina_dict = {"SOCCER": 1}
Australia_dict = {"GOLF":1}
Austria_dict = {"AUTO RACING":1}
Brazil_dict = {"AUTO RACING":1, "SOCCER":2}
Canada_dict = {"BOXING":1, "ICE HOCKEY":1, "HOCKEY":1, "AUTO RACING":1}
Dominican_dict = {"BASEBALL": 1}
Filipino_dict = {"BOXING": 1}
Finland_dict = {"F1 RACING":1}
France_dict = {"AUTO RACING":1}
Germany_dict = {"AUTO RACING": 1, "F1 MOTORSPORTS": 1, "F1 RACING": 1}
Ireland_dict = {"MMA": 1}
Italy_dict = {"MOTORCYCLE GP": 1}
Mexico_dict = {"BOXING": 1}
Northern_Ireland_dict = {"GOLF":1}
Philippines_dict = {"BOXING": 1}
Portugal_dict = {"SOCCER": 1}
Russia_dict = {"ICE HOCKEY": 1}
Serbia_dict = {"TENNIS": 1}
Spain_dict = {"TENNIS": 1}
Switzerland_dict = {"TENNIS": 1}
UK_dict = {"AUTO RACING":2, "SOCCER":1}
USA_dict = {"AMERICAN FOOTBALL":14, "AMERICAN FOOTBALL / BASEBALL":1, "AUTO RACING":1, "AUTO RACING (NASCAR)":2, 
"BASEBALL":3, "BASKETBALL":12,"BOXING":11, "CYCLING":1, "GOLF":6, "NASCAR":2, "NBA":1, "NFL":2,"TENNIS":3}

In [421]:
USA_dict

{'AMERICAN FOOTBALL': 14,
 'AMERICAN FOOTBALL / BASEBALL': 1,
 'AUTO RACING': 1,
 'AUTO RACING (NASCAR)': 2,
 'BASEBALL': 3,
 'BASKETBALL': 12,
 'BOXING': 11,
 'CYCLING': 1,
 'GOLF': 6,
 'NASCAR': 2,
 'NBA': 1,
 'NFL': 2,
 'TENNIS': 3}

### El resultado es Estados Unidos

## 5. ¿Cuántas atletas por deporte tiene cada país?

In [39]:
conteo_por_pais = df1.drop_duplicates("Name")
conteo_por_pais = conteo_por_pais.groupby(["Nationality","Sport"]).size().reset_index(name = "Conteo")
conteo_por_pais.to_excel("conteo_por_pais.xlsx")

In [45]:
conteo_por_pais

Nationality                         Sport  Conteo
0          Argentina                        SOCCER       1
1          Australia                          GOLF       1
2            Austria                   AUTO RACING       1
3             Brazil                   AUTO RACING       1
4             Brazil                        SOCCER       2
5             Canada                   AUTO RACING       1
6             Canada                        BOXING       1
7             Canada                        HOCKEY       1
8             Canada                    ICE HOCKEY       1
9            Finland                     F1 RACING       1
10            France                   AUTO RACING       1
11           Germany                   AUTO RACING       1
12           Ireland                           MMA       1
13             Italy                 MOTORCYCLE GP       1
14            Mexico                        BOXING       1
15  Northern Ireland                          GOLF       1
16       Philippines                        BOXING       1
17          Portugal                        SOCCER       1
18            Russia                    ICE HOCKEY       1
19            Serbia                        TENNIS       1
20             Spain                        TENNIS       1
21       Switzerland                        TENNIS       1
22                UK                   AUTO RACING       2
23                UK                        SOCCER       1
24               USA             AMERICAN FOOTBALL      15
25               USA  AMERICAN FOOTBALL / BASEBALL       1
26               USA          AUTO RACING (NASCAR)       1
27               USA                      BASEBALL       3
28               USA                    BASKETBALL      11
29               USA                        BOXING      11
30               USA                       CYCLING       1
31               USA                          GOLF       5
32               USA                        NASCAR       2
33               USA                           NBA       1
34               USA                           NFL       2
35               USA                        TENNIS       3

## 6. Ganancia mínima y máxima (dentro del conjunto de datos) por deporte y por país.

In [416]:
print(len(set(df2["Sport"])))
print(len(lista_deportes))

20
20


In [419]:
ganancia = pd.DataFrame(lista_deportes)
ganancia.index = ganancia[0]

In [420]:
ganancia[""]

0
0                                                         
BASEBALL                                          BASEBALL
AUTO RACING                                    AUTO RACING
MMA                                                    MMA
NASCAR                                              NASCAR
ICE HOCKEY                                      ICE HOCKEY
BOXING                                              BOXING
BASKETBALL                                      BASKETBALL
TENNIS                                              TENNIS
AMERICAN FOOTBALL / BASEBALL  AMERICAN FOOTBALL / BASEBALL
SOCCER                                              SOCCER
GOLF                                                  GOLF
AMERICAN FOOTBALL                        AMERICAN FOOTBALL
AUTO RACING (NASCAR)                  AUTO RACING (NASCAR)
MOTORCYCLE GP                                MOTORCYCLE GP
NFL                                                    NFL
F1 MOTORSPORTS                              F1 MOTORSPORTS
F1 RACING                                        F1 RACING
CYCLING                                            CYCLING
HOCKEY                                              HOCKEY
NBA                                                    NBA

In [413]:
df2[df2["Sport"] == "AMERICAN FOOTBALL"]

Name Nationality  Current Rank  \
Sport                                                           
AMERICAN FOOTBALL    Peyton Manning         USA             3   
AMERICAN FOOTBALL      Michael Vick         USA             4   
AMERICAN FOOTBALL         Tom Brady         USA             9   
AMERICAN FOOTBALL       Eli Manning         USA             9   
AMERICAN FOOTBALL     Terrell Suggs         USA            10   
AMERICAN FOOTBALL    Peyton Manning         USA            10   
AMERICAN FOOTBALL        Drew Brees         USA             5   
AMERICAN FOOTBALL     Aaron Rodgers         USA             6   
AMERICAN FOOTBALL         Matt Ryan         USA            10   
AMERICAN FOOTBALL        Cam Newton         USA             7   
AMERICAN FOOTBALL       Andrew Luck         USA             6   
AMERICAN FOOTBALL         Matt Ryan         USA             9   
AMERICAN FOOTBALL  Matthew Stafford         USA            10   
AMERICAN FOOTBALL    Russell Wilson         USA             6   
AMERICAN FOOTBALL     Aaron Rodgers         USA             7   
AMERICAN FOOTBALL      Kirk Cousins         USA             9   
AMERICAN FOOTBALL      Carson Wentz         USA            10   

                  Previous Year Rank              Sport  Year  \
Sport                                                           
AMERICAN FOOTBALL                >10  AMERICAN FOOTBALL  2004   
AMERICAN FOOTBALL                >10  AMERICAN FOOTBALL  2005   
AMERICAN FOOTBALL                >10  AMERICAN FOOTBALL  2006   
AMERICAN FOOTBALL                >10  AMERICAN FOOTBALL  2010   
AMERICAN FOOTBALL                >10  AMERICAN FOOTBALL  2010   
AMERICAN FOOTBALL                  7  AMERICAN FOOTBALL  2012   
AMERICAN FOOTBALL                  ?  AMERICAN FOOTBALL  2013   
AMERICAN FOOTBALL                  ?  AMERICAN FOOTBALL  2013   
AMERICAN FOOTBALL               >100  AMERICAN FOOTBALL  2014   
AMERICAN FOOTBALL                >20  AMERICAN FOOTBALL  2016   
AMERICAN FOOTBALL                NaN  AMERICAN FOOTBALL  2017   
AMERICAN FOOTBALL               >100  AMERICAN FOOTBALL  2018   
AMERICAN FOOTBALL               >100  AMERICAN FOOTBALL  2018   
AMERICAN FOOTBALL                 ??  AMERICAN FOOTBALL  2019   
AMERICAN FOOTBALL                 ??  AMERICAN FOOTBALL  2019   
AMERICAN FOOTBALL               >100  AMERICAN FOOTBALL  2020   
AMERICAN FOOTBALL               >100  AMERICAN FOOTBALL  2020   

                   earnings ($ million)  
Sport                                    
AMERICAN FOOTBALL                  42.0  
AMERICAN FOOTBALL                  37.5  
AMERICAN FOOTBALL                  29.0  
AMERICAN FOOTBALL                  39.9  
AMERICAN FOOTBALL                  38.3  
AMERICAN FOOTBALL                  42.4  
AMERICAN FOOTBALL                  51.0  
AMERICAN FOOTBALL                  49.0  
AMERICAN FOOTBALL                  43.8  
AMERICAN FOOTBALL                  53.1  
AMERICAN FOOTBALL                  50.0  
AMERICAN FOOTBALL                  67.3  
AMERICAN FOOTBALL                  59.5  
AMERICAN FOOTBALL                  89.5  
AMERICAN FOOTBALL                  89.3  
AMERICAN FOOTBALL                  60.5  
AMERICAN FOOTBALL                  59.1

In [414]:
df2[df2["Sport"] == "AMERICAN FOOTBALL"].describe()

Current Rank         Year  earnings ($ million)
count     17.000000    17.000000             17.000000
mean       7.647059  2013.764706             53.011765
std        2.316818     5.297752             16.846917
min        3.000000  2004.000000             29.000000
25%        6.000000  2010.000000             42.000000
50%        9.000000  2014.000000             50.000000
75%       10.000000  2018.000000             59.500000
max       10.000000  2020.000000             89.500000

## 7. Atleta con mayores ganancias por deporte por década

En los 1990s es Michael Jordan con 78.3 millones de dolares

In [293]:
l_1990s = df1[df1["Year"] < 2000] 
l_2000s = df1[(df1["Year"] >= 2000) & (df1["Year"] < 2010)]
l_2010s = df1[df1["Year"] >= 2010]


In [301]:
l_1990s["earnings ($ million)"].sort_values(ascending=False)


Year
1997    78.3
1996    75.0
1998    69.0
1991    60.5
1997    54.3
        ... 
1991     8.5
1990     8.5
1990     8.1
1990     8.1
1990     8.1
Name: earnings ($ million), Length: 100, dtype: float64

In [302]:
l_1990s[l_1990s["earnings ($ million)"] == 78.3]

Name Nationality  Current Rank Previous Year Rank       Sport  \
Year                                                                            
1997  Michael Jordan         USA             1                  2  BASKETBALL   

      Year  earnings ($ million)  
Year                              
1997  1997                  78.3

En los 2000s es Tiger Woods con 115 millones de dólares

In [303]:
l_2000s.describe()

Current Rank         Year  earnings ($ million)
count     91.000000    91.000000             91.000000
mean       5.395604  2004.857143             40.594505
std        2.859212     2.783169             19.981037
min        1.000000  2000.000000             20.000000
25%        3.000000  2003.000000             28.000000
50%        5.000000  2005.000000             35.000000
75%        8.000000  2007.000000             45.000000
max       10.000000  2009.000000            115.000000

In [304]:
l_2000s[l_2000s["earnings ($ million)"] == 115]

Name Nationality  Current Rank Previous Year Rank Sport  Year  \
Year                                                                         
2008  Tiger Woods         USA             1                  1  GOLF  2008   

      earnings ($ million)  
Year                        
2008                 115.0

En los 2010s es Floyd Mayweather, con 300 millones de dólares.

In [305]:
l_2010s.describe()

Current Rank        Year  earnings ($ million)
count    110.000000   110.00000            110.000000
mean       5.490909  2015.00000             70.270000
std        2.882231     3.17675             38.098678
min        1.000000  2010.00000             32.300000
25%        3.000000  2012.00000             48.175000
50%        5.500000  2015.00000             60.900000
75%        8.000000  2018.00000             81.050000
max       10.000000  2020.00000            300.000000

In [307]:
l_2010s[l_2010s["earnings ($ million)"] == 300]

Name Nationality  Current Rank Previous Year Rank   Sport  \
Year                                                                          
2015  Floyd Mayweather         USA             1                  1  BOXING   

      Year  earnings ($ million)  
Year                              
2015  2015                 300.0

### Resultado

En los 1990s es Michael Jordan fue el atleta mejor pagado con 78.3 millones de dolares.

En los 2000s fue Tiger Woods con 115 millones de dólares

En los 2010s fue Floyd Mayweather, con 300 millones de dólares.

## 8. Ganancia total por cada deporte por cada año.

In [32]:
df3 = df1.copy()

In [34]:
df3.index=df3["Year"]

In [35]:
df3.head()

Name Nationality  Current Rank Previous Year Rank  \
Year                                                                   
1990         Mike Tyson         USA             1                NaN   
1990     Buster Douglas         USA             2                NaN   
1990  Sugar Ray Leonard         USA             3                NaN   
1990       Ayrton Senna      Brazil             4                NaN   
1990        Alain Prost      France             5                NaN   

            Sport  Year  earnings ($ million)  
Year                                           
1990       BOXING  1990                  28.6  
1990       BOXING  1990                  26.0  
1990       BOXING  1990                  13.0  
1990  AUTO RACING  1990                  10.0  
1990  AUTO RACING  1990                   9.0

In [24]:
setyears = set(df1["Year"])
years1990_2020 = []

for i in setyears:
    years1990_2020.append(i)

print(years1990_2020)

[1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]


In [28]:
ganancia_por_deporte = pd.DataFrame(years1990_2020)
ganancia_por_deporte.index = ganancia_por_deporte[0]


0
0         
1990  1990
1991  1991
1992  1992
1993  1993
1994  1994
1995  1995
1996  1996
1997  1997
1998  1998
1999  1999
2000  2000
2002  2002
2003  2003
2004  2004
2005  2005
2006  2006
2007  2007
2008  2008
2009  2009
2010  2010
2011  2011
2012  2012
2013  2013
2014  2014
2015  2015
2016  2016
2017  2017
2018  2018
2019  2019
2020  2020

In [36]:
ganancia_por_deporte["Sport"] = df3["Sport"]

C:\Users\danie\AppData\Local\Temp\ipykernel_11724\929438824.py:1: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  ganancia_por_deporte["Sport"] = df3["Sport"]


ValueError: cannot reindex on an axis with duplicate labels

## 9. Crea un tablero en Power BI que represente los aspectos más importantes del conjunto de datos, a tu gusto.

In [7]:
df["Sport"] = df["Sport"].str.upper()
print("USA(Golf)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="GOLF")]))
print("USA(Tennis)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="TENNIS")]))
print("USA(NFL)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="NFL")]))
print("USA(Basketball)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="BASKETBALL")]))
print("USA(Boxing)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="BOXING")]))
print("USA(Auto racing)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="AUTO RACING")]))
print("USA(Ice Hockey)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="ICE HOCKEY")]))
print("USA(American Football / Baseball)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("USA(F1 Motorsports)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("USA(NASCAR)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="NASCAR")]))
print("USA(soccer)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="SOCCER")]))
print("USA(American Football)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("USA(cycling)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="CYCLING")]))
print("USA(motorcycle gp)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="MOTORCYCLE GP")]))
print("USA(NBA)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="NBA")]))
print("USA(Baseball)=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="BASEBALL")]))
print("USA(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="USA")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nBrazil(Golf)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="GOLF")]))
print("Brazil(Tennis)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="TENNIS")]))
print("Brazil(NFL)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="NFL")]))
print("Brazil(Basketball)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="BASKETBALL")]))
print("Brazil(Boxing)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="BOXING")]))
print("Brazil(Auto racing)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="AUTO RACING")]))
print("Brazil(Ice Hockey)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="ICE HOCKEY")]))
print("Brazil(American Football / Baseball)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Brazil(F1 Motorsports)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Brazil(NASCAR)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="NASCAR")]))
print("Brazil(soccer)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="SOCCER")]))
print("Brazil(American Football)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Brazil(cycling)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="CYCLING")]))
print("Brazil(motorcycle gp)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Brazil(NBA)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="NBA")]))
print("Brazil(Baseball)=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="BASEBALL")]))
print("Brazil(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Brazil")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nAustralia(Golf)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="GOLF")]))
print("Australia(Tennis)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="TENNIS")]))
print("Australia(NFL)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="NFL")]))
print("Australia(Basketball)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="BASKETBALL")]))
print("Australia(Boxing)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="BOXING")]))
print("Australia(Auto racing)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="AUTO RACING")]))
print("Australia(Ice Hockey)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="ICE HOCKEY")]))
print("Australia(American Football / Baseball)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Australia(F1 Motorsports)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Australia(NASCAR)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="NASCAR")]))
print("Australia(soccer)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="SOCCER")]))
print("Australia(American Football)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Australia(cycling)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="CYCLING")]))
print("Australia(motorcycle gp)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Australia(NBA)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="NBA")]))
print("Australia(Baseball)=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="BASEBALL")]))
print("Australia(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Australia")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nFrance(Golf)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="GOLF")]))
print("France(Tennis)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="TENNIS")]))
print("France(NFL)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="NFL")]))
print("France(Basketball)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="BASKETBALL")]))
print("France(Boxing)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="BOXING")]))
print("France(Auto racing)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="AUTO RACING")]))
print("France(Ice Hockey)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="ICE HOCKEY")]))
print("France(American Football / Baseball)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("France(F1 Motorsports)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("France(NASCAR)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="NASCAR")]))
print("France(soccer)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="SOCCER")]))
print("France(American Football)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("France(cycling)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="CYCLING")]))
print("France(motorcycle gp)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="MOTORCYCLE GP")]))
print("France(NBA)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="NBA")]))
print("France(Baseball)=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="BASEBALL")]))
print("France(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="France")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nCanada(Golf)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="GOLF")]))
print("Canada(Tennis)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="TENNIS")]))
print("Canada(NFL)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="NFL")]))
print("Canada(Basketball)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="BASKETBALL")]))
print("Canada(Boxing)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="BOXING")]))
print("Canada(Auto racing)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="AUTO RACING")]))
print("Canada(F1 racing)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="F1 RACING")]))
print("Canada(Ice Hockey)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="ICE HOCKEY")]))
print("Canada(Hockey)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="HOCKEY")]))
print("Canada(American Football / Baseball)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Canada(F1 Motorsports)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Canada(NASCAR)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="NASCAR")]))
print("Canada(soccer)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="SOCCER")]))
print("Canada(American Football)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Canada(cycling)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="CYCLING")]))
print("Canada(motorcycle gp)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Canada(NBA)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="NBA")]))
print("Canada(Baseball)=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="BASEBALL")]))
print("Canada(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Canada")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nUK(Golf)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="GOLF")]))
print("UK(Tennis)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="TENNIS")]))
print("UK(NFL)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="NFL")]))
print("UK(Basketball)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="BASKETBALL")]))
print("UK(Boxing)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="BOXING")]))
print("UK(Auto racing)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="AUTO RACING")]))
print("UK(Ice Hockey)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="ICE HOCKEY")]))
print("UK(American Football / Baseball)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("UK(F1 Motorsports)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("UK(NASCAR)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="NASCAR")]))
print("UK(soccer)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="SOCCER")]))
print("UK(American Football)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("UK(cycling)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="CYCLING")]))
print("UK(motorcycle gp)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="MOTORCYCLE GP")]))
print("UK(NBA)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="NBA")]))
print("UK(Baseball)=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="BASEBALL")]))
print("UK(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="UK")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nAustria(Golf)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="GOLF")]))
print("Austria(Tennis)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="TENNIS")]))
print("Austria(NFL)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="NFL")]))
print("Austria(Basketball)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="BASKETBALL")]))
print("Austria(Boxing)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="BOXING")]))
print("Austria(Auto racing)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="AUTO RACING")]))
print("Austria(Ice Hockey)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="ICE HOCKEY")]))
print("Austria(American Football / Baseball)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Austria(F1 Motorsports)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Austria(NASCAR)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="NASCAR")]))
print("Austria(soccer)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="SOCCER")]))
print("Austria(American Football)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Austria(cycling)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="CYCLING")]))
print("Austria(motorcycle gp)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Austria(NBA)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="NBA")]))
print("Austria(Baseball)=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="BASEBALL")]))
print("Austria(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Austria")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nGermany(Golf)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="GOLF")]))
print("Germany(Tennis)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="TENNIS")]))
print("Germany(NFL)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="NFL")]))
print("Germany(Basketball)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="BASKETBALL")]))
print("Germany(Boxing)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="BOXING")]))
print("Germany(Auto racing)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="AUTO RACING")]))
print("Germany(Ice Hockey)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="ICE HOCKEY")]))
print("Germany(American Football / Baseball)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Germany(F1 Motorsports)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Germany(NASCAR)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="NASCAR")]))
print("Germany(soccer)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="SOCCER")]))
print("Germany(American Football)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Germany(cycling)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="CYCLING")]))
print("Germany(motorcycle gp)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Germany(NBA)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="NBA")]))
print("Germany(Baseball)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="BASEBALL")]))
print("Germany(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="AUTO RACING (NASCAR)")]))
print("Germany(F1 Racing)=",len(df[(df["Nationality"] =="Germany")&(df["Sport"] =="F1 RACING")]))

print("\nRussia(Golf)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="GOLF")]))
print("Russia(Tennis)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="TENNIS")]))
print("Russia(NFL)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="NFL")]))
print("Russia(Basketball)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="BASKETBALL")]))
print("Russia(Boxing)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="BOXING")]))
print("Russia(Auto racing)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="AUTO RACING")]))
print("Russia(Ice Hockey)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="ICE HOCKEY")]))
print("Russia(American Football / Baseball)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Russia(F1 Motorsports)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Russia(NASCAR)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="NASCAR")]))
print("Russia(soccer)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="SOCCER")]))
print("Russia(American Football)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Russia(cycling)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="CYCLING")]))
print("Russia(motorcycle gp)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Russia(NBA)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="NBA")]))
print("Russia(Baseball)=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="BASEBALL")]))
print("Russia(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Russia")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nFinland(Golf)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="GOLF")]))
print("Finland(Tennis)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="TENNIS")]))
print("Finland(NFL)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="NFL")]))
print("Finland(Basketball)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="BASKETBALL")]))
print("Finland(Boxing)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="BOXING")]))
print("Finland(Auto racing)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="AUTO RACING")]))
print("Finland(F1 racing)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="F1 RACING")]))
print("Finland(Ice Hockey)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="ICE HOCKEY")]))
print("Finland(American Football / Baseball)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Finland(F1 Motorsports)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Finland(NASCAR)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="NASCAR")]))
print("Finland(soccer)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="SOCCER")]))
print("Finland(American Football)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Finland(cycling)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="CYCLING")]))
print("Finland(motorcycle gp)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Finland(NBA)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="NBA")]))
print("Finland(Baseball)=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="BASEBALL")]))
print("Finland(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Finland")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nSwitzerland(Golf)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="GOLF")]))
print("Switzerland(Tennis)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="TENNIS")]))
print("Switzerland(NFL)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="NFL")]))
print("Switzerland(Basketball)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="BASKETBALL")]))
print("Switzerland(Boxing)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="BOXING")]))
print("Switzerland(Auto racing)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="AUTO RACING")]))
print("Switzerland(Ice Hockey)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="ICE HOCKEY")]))
print("Switzerland(American Football / Baseball)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Switzerland(F1 Motorsports)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Switzerland(NASCAR)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="NASCAR")]))
print("Switzerland(soccer)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="SOCCER")]))
print("Switzerland(American Football)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Switzerland(cycling)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="CYCLING")]))
print("Switzerland(motorcycle gp)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Switzerland(NBA)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="NBA")]))
print("Switzerland(Baseball)=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="BASEBALL")]))
print("Switzerland(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Switzerland")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nItaly(Golf)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="GOLF")]))
print("Italy(Tennis)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="TENNIS")]))
print("Italy(NFL)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="NFL")]))
print("Italy(Basketball)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="BASKETBALL")]))
print("Italy(Boxing)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="BOXING")]))
print("Italy(Auto racing)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="AUTO RACING")]))
print("Italy(Ice Hockey)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="ICE HOCKEY")]))
print("Italy(American Football / Baseball)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Italy(F1 Motorsports)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Italy(NASCAR)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="NASCAR")]))
print("Italy(soccer)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="SOCCER")]))
print("Italy(American Football)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Italy(cycling)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="CYCLING")]))
print("Italy(motorcycle gp)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Italy(NBA)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="NBA")]))
print("Italy(Baseball)=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="BASEBALL")]))
print("Italy(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Italy")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nPhilippines(Golf)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="GOLF")]))
print("Philippines(Tennis)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="TENNIS")]))
print("Philippines(NFL)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="NFL")]))
print("Philippines(Basketball)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="BASKETBALL")]))
print("Philippines(Boxing)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="BOXING")]))
print("Philippines(Auto racing)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="AUTO RACING")]))
print("Philippines(Ice Hockey)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="ICE HOCKEY")]))
print("Philippines(American Football / Baseball)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Philippines(F1 Motorsports)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Philippines(NASCAR)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="NASCAR")]))
print("Philippines(soccer)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="SOCCER")]))
print("Philippines(American Football)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Philippines(cycling)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="CYCLING")]))
print("Philippines(motorcycle gp)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Philippines(NBA)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="NBA")]))
print("Philippines(Baseball)=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="BASEBALL")]))
print("Philippines(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Philippines")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nPortugal(Golf)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="GOLF")]))
print("Portugal(Tennis)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="TENNIS")]))
print("Portugal(NFL)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="NFL")]))
print("Portugal(Basketball)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="BASKETBALL")]))
print("Portugal(Boxing)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="BOXING")]))
print("Portugal(Auto racing)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="AUTO RACING")]))
print("Portugal(Ice Hockey)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="ICE HOCKEY")]))
print("Portugal(American Football / Baseball)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Portugal(F1 Motorsports)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Portugal(NASCAR)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="NASCAR")]))
print("Portugal(soccer)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="SOCCER")]))
print("Portugal(American Football)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Portugal(cycling)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="CYCLING")]))
print("Portugal(motorcycle gp)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Portugal(NBA)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="NBA")]))
print("Portugal(Baseball)=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="BASEBALL")]))
print("Portugal(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Portugal")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nDominican(Golf)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="GOLF")]))
print("Dominican(Tennis)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="TENNIS")]))
print("Dominican(NFL)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="NFL")]))
print("Dominican(Basketball)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="BASKETBALL")]))
print("Dominican(Boxing)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="BOXING")]))
print("Dominican(Auto racing)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="AUTO RACING")]))
print("Dominican(Ice Hockey)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="ICE HOCKEY")]))
print("Dominican(American Football / Baseball)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Dominican(F1 Motorsports)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Dominican(NASCAR)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="NASCAR")]))
print("Dominican(soccer)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="SOCCER")]))
print("Dominican(American Football)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Dominican(cycling)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="CYCLING")]))
print("Dominican(motorcycle gp)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Dominican(NBA)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="NBA")]))
print("Dominican(Baseball)=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="BASEBALL")]))
print("Dominican(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Dominican")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nArgentina(Golf)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="GOLF")]))
print("Argentina(Tennis)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="TENNIS")]))
print("Argentina(NFL)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="NFL")]))
print("Argentina(Basketball)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="BASKETBALL")]))
print("Argentina(Boxing)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="BOXING")]))
print("Argentina(Auto racing)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="AUTO RACING")]))
print("Argentina(Ice Hockey)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="ICE HOCKEY")]))
print("Argentina(American Football / Baseball)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Argentina(F1 Motorsports)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Argentina(NASCAR)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="NASCAR")]))
print("Argentina(soccer)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="SOCCER")]))
print("Argentina(American Football)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Argentina(cycling)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="CYCLING")]))
print("Argentina(motorcycle gp)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Argentina(NBA)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="NBA")]))
print("Argentina(Baseball)=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="BASEBALL")]))
print("Argentina(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Argentina")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nFilipino(Golf)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="GOLF")]))
print("Filipino(Tennis)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="TENNIS")]))
print("Filipino(NFL)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="NFL")]))
print("Filipino(Basketball)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="BASKETBALL")]))
print("Filipino(Boxing)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="BOXING")]))
print("Filipino(Auto racing)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="AUTO RACING")]))
print("Filipino(Ice Hockey)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="ICE HOCKEY")]))
print("Filipino(American Football / Baseball)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Filipino(F1 Motorsports)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Filipino(NASCAR)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="NASCAR")]))
print("Filipino(soccer)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="SOCCER")]))
print("Filipino(American Football)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Filipino(cycling)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="CYCLING")]))
print("Filipino(motorcycle gp)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Filipino(NBA)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="NBA")]))
print("Filipino(Baseball)=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="BASEBALL")]))
print("Filipino(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Filipino")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nNorthern Ireland(Golf)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="GOLF")]))
print("Northern Ireland(Tennis)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="TENNIS")]))
print("Northern Ireland(NFL)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="NFL")]))
print("Northern Ireland(Basketball)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="BASKETBALL")]))
print("Northern Ireland(Boxing)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="BOXING")]))
print("Northern Ireland(Auto racing)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="AUTO RACING")]))
print("Northern Ireland(Ice Hockey)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="ICE HOCKEY")]))
print("Northern Ireland(American Football / Baseball)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Northern Ireland(F1 Motorsports)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Northern Ireland(NASCAR)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="NASCAR")]))
print("Northern Ireland(soccer)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="SOCCER")]))
print("Northern Ireland(American Football)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Northern Ireland(cycling)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="CYCLING")]))
print("Northern Ireland(motorcycle gp)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Northern Ireland(NBA)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="NBA")]))
print("Northern Ireland(Baseball)=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="BASEBALL")]))
print("Northern Ireland(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Northern Ireland")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

print("\nMexico(Golf)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="GOLF")]))
print("Mexico(Tennis)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="TENNIS")]))
print("Mexico(NFL)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="NFL")]))
print("Mexico(Basketball)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="BASKETBALL")]))
print("Mexico(Boxing)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="BOXING")]))
print("Mexico(Auto racing)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="AUTO RACING")]))
print("Mexico(Ice Hockey)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="ICE HOCKEY")]))
print("Mexico(American Football / Baseball)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="AMERICAN FOOTBALL / BASEBALL")]))
print("Mexico(F1 Motorsports)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="F1 MOTORSPORTS")]))
print("Mexico(NASCAR)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="NASCAR")]))
print("Mexico(soccer)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="SOCCER")]))
print("Mexico(American Football)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="AMERICAN FOOTBALL")]))
print("Mexico(cycling)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="CYCLING")]))
print("Mexico(motorcycle gp)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="MOTORCYCLE GP")]))
print("Mexico(NBA)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="NBA")]))
print("Mexico(Baseball)=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="BASEBALL")]))
print("Mexico(Auto Racing (Nascar))=",len(df[(df["Nationality"] =="Mexico")&(df["Sport"] =="AUTO RACING (NASCAR)")]))

USA(Golf)= 42
USA(Tennis)= 9
USA(NFL)= 3
USA(Basketball)= 81
USA(Boxing)= 40
USA(Auto racing)= 1
USA(Ice Hockey)= 0
USA(American Football / Baseball)= 1
USA(F1 Motorsports)= 0
USA(NASCAR)= 3
USA(soccer)= 0
USA(American Football)= 17
USA(cycling)= 1
USA(motorcycle gp)= 0
USA(NBA)= 1
USA(Baseball)= 5
USA(Auto Racing (Nascar))= 2

Brazil(Golf)= 0
Brazil(Tennis)= 0
Brazil(NFL)= 0
Brazil(Basketball)= 0
Brazil(Boxing)= 0
Brazil(Auto racing)= 4
Brazil(Ice Hockey)= 0
Brazil(American Football / Baseball)= 0
Brazil(F1 Motorsports)= 0
Brazil(NASCAR)= 0
Brazil(soccer)= 5
Brazil(American Football)= 0
Brazil(cycling)= 0
Brazil(motorcycle gp)= 0
Brazil(NBA)= 0
Brazil(Baseball)= 0
Brazil(Auto Racing (Nascar))= 0

Australia(Golf)= 1
Australia(Tennis)= 0
Australia(NFL)= 0
Australia(Basketball)= 0
Australia(Boxing)= 0
Australia(Auto racing)= 0
Australia(Ice Hockey)= 0
Australia(American Football / Baseball)= 0
Australia(F1 Motorsports)= 0
Australia(NASCAR)= 0
Australia(soccer)= 0
Australia(American Footb